apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  profile: empty
  hub: gcr.io/istio-release
  components:
    base:
      enabled: true
    pilot:
      enabled: true
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        serviceAnnotations:
          networking.gke.io/load-balancer-type: Internal
          networking.gke.io/internal-load-balancer-allow-global-access: "true"
